import MainHeader from '@/components/mainHeader'
import './globals.css'
import { Inter } from 'next/font/google'
import MainFooter from '@/components/mainFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-cyan-950 md:h-screen  text-white'}>
        <div className='bg-black opacity-80 md:h-screen '>
          <section className='mx-[5%]'>
            <MainHeader />
          </section>
          <section className='mx-[5%]'>
            {children}
          </section>
          <section className='mx-[5%]'>
            <MainFooter />
          </section >
        </div>
      </body>
    </html>
  )
}
